name: Build

permissions:
  contents: write

on:
  release:
    types: [created]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/*"
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/*"

env:
  BUILD_DIR: build
  RESOURCES_DIR: ${{ github.workspace }}/resources
  ARTIFACT_DIR: ${{ github.workspace }}/build
  ARTIFACT_NAME: Lugormod-${{ github.event.release.tag_name }}

jobs:
  windows-build:
    name: Windows ${{ matrix.arch }} ${{ matrix.build_type }}
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86]
        build_type: [Debug, Release]
        include:
          - arch: x86
            platform: Win32
    steps:
      - name: Checkout repository and branch
        uses: 'actions/checkout@v4'

      - name: Add `msbuild` to PATH
        uses: 'microsoft/setup-msbuild@v1.1'

      - name: Setup
        run: cmake -B ${{ env.BUILD_DIR }} -A ${{ matrix.platform }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build codebase
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.build_type }} -j $NUMBER_OF_PROCESSORS 2>&1 | Out-File -FilePath ${{ github.workspace }}/build/compile.log

      - name: Install binaries
        if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
        run: cmake --install ${{ github.workspace }}\${{ env.BUILD_DIR }} --config ${{ matrix.build_type }} --prefix ${{ env.RESOURCES_DIR }}\GameData

      - name: Create zip archive
        if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
        run: Compress-Archive -Path ${{ env.RESOURCES_DIR }}\* -DestinationPath "${{ env.ARTIFACT_DIR }}\${{ env.ARTIFACT_NAME }}-${{ runner.os }}-${{ matrix.arch }}.zip"

      - name: Upload artifact
        uses: 'actions/upload-artifact@v4'
        if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
        with:
          name: Lugormod ${{ github.event.release.name }} - ${{ runner.os }} ${{ matrix.arch }}
          path: ${{ env.ARTIFACT_DIR }}\${{ env.ARTIFACT_NAME }}-${{ runner.os }}-${{ matrix.arch }}.zip

      - name: Publish release files
        if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
        uses: 'actions/github-script@v7'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const upload = require('./.github/scripts/upload.js')
            await upload({github, context, core})


  linux-build:
    name: Linux ${{ matrix.arch }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86]
        build_type: [Debug, Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]
    steps:
    - name: Checkout repository and branch
      uses: 'actions/checkout@v4'

    - name: Fetch build dependencies
      run: |
        if [ ${{ matrix.arch }} == "x86" ]; then
          sudo dpkg --add-architecture i386
          sudo apt -qq update
          sudo apt install -y gcc-multilib g++-multilib libc6-dev-i386
        else
          sudo apt-get -qq update
        fi

    - name: Setup
      run: |
        cmake -B ${{ env.BUILD_DIR }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build codebase
      run: cmake --build ${{ env.BUILD_DIR }} -j $(nproc) 2>&1 | tee ${{ github.workspace }}/build/compile.log

    - name: Install binaries
      if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
      run: cmake --install ${{ env.BUILD_DIR }} --config ${{ matrix.build_type }} --prefix ${{ env.RESOURCES_DIR }}/GameData

    - name: Create tar archive
      if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
      run: tar -czvf ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}-${{ runner.os }}-${{ matrix.arch }}.tar.gz -C ${{ env.RESOURCES_DIR }} .

    - name: Upload artifact
      uses: 'actions/upload-artifact@v4'
      if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
      with:
        name: Lugormod ${{ github.event.release.name }} - ${{ runner.os }} ${{ matrix.arch }}
        path:  ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}-${{ runner.os }}-${{ matrix.arch }}.tar.gz

    - name: Publish release files
      uses: 'actions/github-script@v7'
      if: ${{ matrix.build_type == 'Release' && github.event_name == 'release' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const upload = require('./.github/scripts/upload.js')
          await upload({github, context, core})
